export const teams = [ 
  { 
    ballPark: 'Oriole Park',
    id: 1,
    teamName: 'Baltimore Orioles',
    website: 'orioles.com',
    urlCode: 'bal',
    roster: [ 
      { firstName: 'Keegan', lastName: 'Akin' },
      { firstName: 'Shawn', lastName: 'Armstrong' },
      { firstName: 'Brandon', lastName: 'Bailey' },
      { firstName: 'Richard', lastName: 'Bleier' },
      { firstName: 'Cody', lastName: 'Carroll' },
      { firstName: 'Miguel', lastName: 'Castro' },
      { firstName: 'Alex', lastName: 'Cobb' },
      { firstName: 'Paul', lastName: 'Fry' },
      { firstName: 'Mychal', lastName: 'Givens' },
      { firstName: 'Hunter', lastName: 'Harvey' },
      { firstName: 'David', lastName: 'Hess' },
      { firstName: 'Branden', lastName: 'Kline' },
      { firstName: 'Dean', lastName: 'Kremer' },
      { firstName: 'John', lastName: 'Means' },
      { firstName: 'Evan', lastName: 'Phillips' },
      { firstName: 'Michael', lastName: 'Rucker' },
      { firstName: 'Tanner', lastName: 'Scott' },
      { firstName: 'Kohl', lastName: 'Stewart' },
      { firstName: 'Cole', lastName: 'Sulser' },
      { firstName: 'Dillon', lastName: 'Tate' },
      { firstName: 'Asher', lastName: 'Wojciechowski' },
      { firstName: 'Pedro', lastName: 'Severino' },
      { firstName: 'Chance', lastName: 'Sisco' },
      { firstName: 'Austin', lastName: 'Wynns' },
      { firstName: 'Hanser', lastName: 'Alberto' },
      { firstName: 'Chris', lastName: 'Davis' },
      { firstName: 'Jose', lastName: 'Iglesias' },
      { firstName: 'Richie', lastName: 'Martin' },
      { firstName: 'Ryan', lastName: 'Mountcastle' },
      { firstName: 'Renato', lastName: 'Nunez' },
      { firstName: 'Rio', lastName: 'Ruiz' },
      { firstName: 'Richard', lastName: 'Urena' },
      { firstName: 'Austin', lastName: 'Hays' },
      { firstName: 'Trey', lastName: 'Mancini' },
      { firstName: 'Ryan', lastName: 'McKenna' },
      { firstName: 'Cedric', lastName: 'Mullins' },
      { firstName: 'Anthony', lastName: 'Santander' },
      { firstName: 'Dwight', lastName: 'Smith' },
      { firstName: 'DJ', lastName: 'Stewart' },
      { firstName: 'Stevie', lastName: 'Wilkerson' } 
    ]
  },
  { 
    ballPark: 'Fenway Park',
    id: 2,
    teamName: 'Boston Red Sox',
    website: 'redsox.com',
    urlCode: 'bos',
    roster: [ 
      { firstName: 'Yoan', lastName: 'Aybar' },
      { firstName: 'Matt', lastName: 'Barnes' },
      { firstName: 'Ryan', lastName: 'Brasier' },
      { firstName: 'Colten', lastName: 'Brewer' },
      { firstName: 'Austin', lastName: 'Brice' },
      { firstName: 'Nathan', lastName: 'Eovaldi' },
      { firstName: 'Matt', lastName: 'Hall' },
      { firstName: 'Kyle', lastName: 'Hart' },
      { firstName: 'Heath', lastName: 'Hembree' },
      { firstName: 'Darwinzon', lastName: 'Hernandez' },
      { firstName: 'Chris', lastName: 'Mazza' },
      { firstName: 'Josh', lastName: 'Osich' },
      { firstName: 'Martin', lastName: 'Perez' },
      { firstName: 'David', lastName: 'Price' },
      { firstName: 'Eduardo', lastName: 'Rodriguez' },
      { firstName: 'Chris', lastName: 'Sale' },
      { firstName: 'Mike', lastName: 'Shawaryn' },
      { firstName: 'Jeffrey', lastName: 'Springs' },
      { firstName: 'Josh', lastName: 'Taylor' },
      { firstName: 'Hector', lastName: 'Velazquez' },
      { firstName: 'Marcus', lastName: 'Walden' },
      { firstName: 'Ryan', lastName: 'Weber' },
      { firstName: 'Brandon', lastName: 'Workman' },
      { firstName: 'Kevin', lastName: 'Plawecki' },
      { firstName: 'Christian', lastName: 'Vazquez' },
      { firstName: 'Jonathan', lastName: 'Arauz' },
      { firstName: 'Xander', lastName: 'Bogaerts' },
      { firstName: 'C.J.', lastName: 'Chatham' },
      { firstName: 'Michael', lastName: 'Chavis' },
      { firstName: 'Bobby', lastName: 'Dalbec' },
      { firstName: 'Rafael', lastName: 'Devers' },
      { firstName: 'Tzu-Wei', lastName: 'Lin' },
      { firstName: 'Mitch', lastName: 'Moreland' },
      { firstName: 'Dustin', lastName: 'Pedroia' },
      { firstName: 'Jose', lastName: 'Peraza' },
      { firstName: 'Andrew', lastName: 'Benintendi' },
      { firstName: 'Mookie', lastName: 'Betts' },
      { firstName: 'Jackie', lastName: 'Bradley' },
      { firstName: 'J.D.', lastName: 'Martinez' },
      { firstName: 'Marcus', lastName: 'Wilson' }
    ]
  },
  { 
    ballPark: 'Guaranteed Rate Field',
    id: 3,
    teamName: 'Chicago White Sox',
    website: 'whitesox.com',
    urlCode: 'cws',
    roster: [
      { firstName: 'Aaron', lastName: 'Bummer' },
      { firstName: 'Zack', lastName: 'Burdi' },
      { firstName: 'Dylan', lastName: 'Cease' },
      { firstName: 'Steve', lastName: 'Cishek' },
      { firstName: 'Alex', lastName: 'Colome' },
      { firstName: 'Jimmy', lastName: 'Cordero' },
      { firstName: 'Dane', lastName: 'Dunning' },
      { firstName: 'Bernardo', lastName: 'Flores' },
      { firstName: 'Matt', lastName: 'Foster' },
      { firstName: 'Jace', lastName: 'Fry' },
      { firstName: 'Carson', lastName: 'Fulmer' },
      { firstName: 'Lucas', lastName: 'Giolito' },
      { firstName: 'Gio', lastName: 'Gonzalez' },
      { firstName: 'Ian', lastName: 'Hamilton' },
      { firstName: 'Kelvin', lastName: 'Herrera' },
      { firstName: 'Dallas', lastName: 'Keuchel' },
      { firstName: 'Michael', lastName: 'Kopech' },
      { firstName: 'Jimmy', lastName: 'Lambert' },
      { firstName: 'Reynaldo', lastName: 'Lopez' },
      { firstName: 'Evan', lastName: 'Marshall' },
      { firstName: 'Carlos', lastName: 'Rodon' },
      { firstName: 'Jose', lastName: 'Ruiz' },
      { firstName: 'Zack', lastName: 'Collins' },
      { firstName: 'Yasmani', lastName: 'Grandal' },
      { firstName: 'James', lastName: 'McCann' },
      { firstName: 'Yermin', lastName: 'Mercedes' },
      { firstName: 'Seby', lastName: 'Zavala' },
      { firstName: 'Jose', lastName: 'Abreu' },
      { firstName: 'Tim', lastName: 'Anderson' },
      { firstName: 'Edwin', lastName: 'Encarnacion' },
      { firstName: 'Danny', lastName: 'Mendick' },
      { firstName: 'Yoan', lastName: 'Moncada' },
      { firstName: 'Micker', lastName: 'Adolfo' },
      { firstName: 'Luis', lastName: 'Alexander' },
      { firstName: 'Nicky', lastName: 'Delmonico' },
      { firstName: 'Nicky', lastName: 'Delmonico' },
      { firstName: 'Adam', lastName: 'Engel' },
      { firstName: 'Leury', lastName: 'Garcia' },
      { firstName: 'Eloy', lastName: 'Jimenez' },
      { firstName: 'Nomar', lastName: 'Mazara' },
      { firstName: 'Luis', lastName: 'Robert' },
      { firstName: 'Blake', lastName: 'Rutherford' }
    ]
  },
  { 
    ballPark: 'Progressive Field',
    id: 4,
    teamName: 'Cleveland Indians',
    website: 'indians.com',
    urlCode: 'cle',
    roster: [
      { firstName: 'Logan', lastName: 'Allen' },
      { firstName: 'Shane', lastName: 'Bieber' },
      { firstName: 'Carlos', lastName: 'Carrasco' },
      { firstName: 'Adam', lastName: 'Cimber' },
      { firstName: 'Aaron', lastName: 'Civale' },
      { firstName: 'Emmanuel', lastName: 'Clase' },
      { firstName: 'Mike', lastName: 'Clevinger' },
      { firstName: 'Brad', lastName: 'Hand' },
      { firstName: 'Sam', lastName: 'Hentges' },
      { firstName: 'James', lastName: 'Hoyt' },
      { firstName: 'James', lastName: 'Karinchak' },
      { firstName: 'Phil', lastName: 'Maton' },
      { firstName: 'Triston', lastName: 'McKenzie' },
      { firstName: 'Jean', lastName: 'Carlos' },
      { firstName: 'Scott', lastName: 'Moss' },
      { firstName: 'Oliver', lastName: 'Perez' },
      { firstName: 'Zach', lastName: 'Plesac' },
      { firstName: 'Adam', lastName: 'Plutko' },
      { firstName: 'Jefry', lastName: 'Rodriguez' },
      { firstName: 'Nick', lastName: 'Wittgren' },
      { firstName: 'Hunter', lastName: 'Wood' },
      { firstName: 'Sandy', lastName: 'Leon' },
      { firstName: 'Roberto', lastName: 'Perez' },
      { firstName: 'Christian', lastName: 'Arroyo' },
      { firstName: 'Bobby', lastName: 'Bradley' },
      { firstName: 'Yu', lastName: 'Chang' },
      { firstName: 'Cesar', lastName: 'Hernandez' },
      { firstName: 'Francisco', lastName: 'Lindor' },
      { firstName: 'Jose', lastName: 'Ramirez' },
      { firstName: 'Carlos', lastName: 'Santana' },
      { firstName: 'Andrew', lastName: 'Velazquez' },
      { firstName: 'Greg', lastName: 'Allen' },
      { firstName: 'Jake', lastName: 'Bauers' },
      { firstName: 'Delino', lastName: 'DeShields' },
      { firstName: 'Daniel', lastName: 'Johnson' },
      { firstName: 'Jordan', lastName: 'Luplow' },
      { firstName: 'Oscar', lastName: 'Mercado' },
      { firstName: 'Tyler', lastName: 'Naquin' },
      { firstName: 'Franmil', lastName: 'Reyes' },
      { firstName: 'Bradley', lastName: 'Zimmer' }
    ]
  },
  { 
    ballPark: 'Comerica Park',
    id: 5,
    teamName: 'Detroit Tigers',
    website: 'tigers.com',
    urlCode: 'det',
    roster: [
      { firstName: 'Tyler', lastName: 'Alexander' },
      { firstName: 'Matthew', lastName: 'Boyd' },
      { firstName: 'Beau', lastName: 'Burrows' },
      { firstName: 'Anthony', lastName: 'Castro' },
      { firstName: 'Jose', lastName: 'Cisnero' },
      { firstName: 'Buck', lastName: 'Farmer' },
      { firstName: 'Michael', lastName: 'Fulmer' },
      { firstName: 'Kyle', lastName: 'Funkhouser' },
      { firstName: 'Bryan', lastName: 'Garcia' },
      { firstName: 'Rony', lastName: 'Garcia' },
      { firstName: 'Joe', lastName: 'Jimenez' },
      { firstName: 'David', lastName: 'McKay' },
      { firstName: 'Daniel', lastName: 'Norris' },
      { firstName: 'Ivan', lastName: 'Nova' },
      { firstName: 'Franklin', lastName: 'Perez' },
      { firstName: 'John', lastName: 'Schreiber' },
      { firstName: 'Gregory', lastName: 'Soto' },
      { firstName: 'Spencer', lastName: 'Turnbull' },
      { firstName: 'Jordan', lastName: 'Zimmermann' },
      { firstName: 'Grayson', lastName: 'Greiner' },
      { firstName: 'Eric', lastName: 'Haase' },
      { firstName: 'Jake', lastName: 'Rogers' },
      { firstName: 'Austin', lastName: 'Romine' },
      { firstName: 'Sergio', lastName: 'Alcantara' },
      { firstName: 'Miguel', lastName: 'Cabrera' },
      { firstName: 'Jeimer', lastName: 'Candelario' },
      { firstName: 'Harold', lastName: 'Castro' },
      { firstName: 'Willi', lastName: 'Castro' },
      { firstName: 'C.J.', lastName: 'Cron' },
      { firstName: 'Dawel', lastName: 'Lugo' },
      { firstName: 'Isaac', lastName: 'Paredes' },
      { firstName: 'Jonathan', lastName: 'Schoop' },
      { firstName: 'Daz', lastName: 'Cameron' },
      { firstName: 'Travis', lastName: 'Demeritte' },
      { firstName: 'Niko', lastName: 'Goodrum' },
      { firstName: 'Derek', lastName: 'Hill' },
      { firstName: 'JaCoby', lastName: 'Jones' },
      { firstName: 'Victor', lastName: 'Reyes' },
      { firstName: 'Christin', lastName: 'Stewart' },
      { firstName: 'Troy', lastName: 'Stokes' }
    ]
  },
  { 
    ballPark: 'Minute Maid Park',
    id: 6,
    teamName: 'Houston Astros',
    website: 'astros.com',
    urlCode: 'hou',
    roster: [
      { firstName: 'Bryan', lastName: 'Abreu' },
      { firstName: 'Rogelio', lastName: 'Armenteros' },
      { firstName: 'Joe', lastName: 'Biagini' },
      { firstName: 'Chris', lastName: 'Devenski' },
      { firstName: 'Kent', lastName: 'Emanuel' },
      { firstName: 'Zack', lastName: 'Greinke' },
      { firstName: 'Josh', lastName: 'James' },
      { firstName: 'Cristian', lastName: 'Javier' },
      { firstName: 'Francis', lastName: 'Martes' },
      { firstName: 'Lance', lastName: 'McCullers' },
      { firstName: 'Roberto', lastName: 'Osuna' },
      { firstName: 'Enoli', lastName: 'Paredes' },
      { firstName: 'Brad', lastName: 'Peacock' },
      { firstName: 'Cionel', lastName: 'Perez' },
      { firstName: 'Ryan', lastName: 'Pressly' },
      { firstName: 'Austin', lastName: 'Pruitt' },
      { firstName: 'Nivaldo', lastName: 'Rodriguez' },
      { firstName: 'Joe', lastName: 'Smith' },
      { firstName: 'Cy', lastName: 'Sneed' },
      { firstName: 'Blake', lastName: 'Taylor' },
      { firstName: 'Jose', lastName: 'Urquidy' },
      { firstName: 'Framber', lastName: 'Valdez' },
      { firstName: 'Justin', lastName: 'Verlander' },
      { firstName: 'Dustin', lastName: 'Garneau' },
      { firstName: 'Martin', lastName: 'Maldonado' },
      { firstName: 'Garrett', lastName: 'Stubbs' },
      { firstName: 'Jose', lastName: 'Altuve' },
      { firstName: 'Alex', lastName: 'Bregman' },
      { firstName: 'Carlos', lastName: 'Correa' },
      { firstName: 'Aledmys', lastName: 'Diaz' },
      { firstName: 'Yuli', lastName: 'Gurriel' },
      { firstName: 'Taylor', lastName: 'Jones' },
      { firstName: 'Jack', lastName: 'Mayfield' },
      { firstName: 'Abraham', lastName: 'Toro' },
      { firstName: 'Yordan', lastName: 'Alvarez' },
      { firstName: 'Michael', lastName: 'Brantley' },
      { firstName: 'Josh', lastName: 'Reddick' },
      { firstName: 'George', lastName: 'Springer' },
      { firstName: 'Myles', lastName: 'Straw' },
      { firstName: 'Kyle', lastName: 'Tucker' }
    ]
  },
  { 
    ballPark: 'Kauffman Stadium',
    id: 7,
    teamName: 'Kansas City Royals',
    website: 'royals.com',
    urlCode: 'kc',
    roster: [
      { firstName: 'Chance', lastName: 'Adams' },
      { firstName: 'Scott', lastName: 'Barlow' },
      { firstName: 'Scott', lastName: 'Blewett' },
      { firstName: 'Danny', lastName: 'Duffy' },
      { firstName: 'Foster', lastName: 'Griffin' },
      { firstName: 'Jesse', lastName: 'Hahn' },
      { firstName: 'Carlos', lastName: 'Hernandez' },
      { firstName: 'Tim', lastName: 'Hill' },
      { firstName: 'Jakob', lastName: 'Junis' },
      { firstName: 'Brad', lastName: 'Keller' },
      { firstName: 'Ian', lastName: 'Kennedy' },
      { firstName: 'Jorge', lastName: 'Lopez' },
      { firstName: 'Richard', lastName: 'Lovelady' },
      { firstName: 'Kevin', lastName: 'McCarthy' },
      { firstName: 'Mike', lastName: 'Montgomery' },
      { firstName: 'Jake', lastName: 'Newberry' },
      { firstName: 'Randy', lastName: 'Rosario' },
      { firstName: 'Eric', lastName: 'Skoglund' },
      { firstName: 'Glenn', lastName: 'Sparkman' },
      { firstName: 'Gabe', lastName: 'Speier' },
      { firstName: 'Josh', lastName: 'Staumont' },
      { firstName: 'Stephen', lastName: 'Woods' },
      { firstName: 'Kyle', lastName: 'Zimmer' },
      { firstName: 'Cam', lastName: 'Gallagher' },
      { firstName: 'Salvador', lastName: 'Perez' },
      { firstName: 'Meibrys', lastName: 'Viloria' },
      { firstName: 'Hunter', lastName: 'Dozier' },
      { firstName: 'Maikel', lastName: 'Franco' },
      { firstName: 'Kelvin', lastName: 'Gutierrez' },
      { firstName: 'Jeison', lastName: 'Guzman' },
      { firstName: 'Nicky', lastName: 'Lopez' },
      { firstName: 'Ryan', lastName: 'McBroom' },
      { firstName: 'Whit', lastName: 'Merrifield' },
      { firstName: 'Adalberto', lastName: 'Mondesi' },
      { firstName: 'Ryan', lastName: 'O\'Hearn' },
      { firstName: 'Alex', lastName: 'Gordon' },
      { firstName: 'Nick', lastName: 'Heath' },
      { firstName: 'Brett', lastName: 'Phillips' },
      { firstName: 'Jorge', lastName: 'Soler' },
      { firstName: 'Bubba', lastName: 'Starling' }
    ]
  },
  { 
    ballPark: 'Angel Stadium',
    id: 8,
    teamName: 'Los Angeles Angels',
    website: 'angels.com',
    urlCode: 'ana',
    roster: [
      { firstName: 'Justin', lastName: 'Anderson' },
      { firstName: 'Matt', lastName: 'Andriese' },
      { firstName: 'Luke', lastName: 'Bard' },
      { firstName: 'Jaime', lastName: 'Barria' },
      { firstName: 'Cam', lastName: 'Bedrosian' },
      { firstName: 'Dylan', lastName: 'Bundy' },
      { firstName: 'Ty', lastName: 'Buttrey' },
      { firstName: 'Griffin', lastName: 'Canning' },
      { firstName: 'Taylor', lastName: 'Cole' },
      { firstName: 'Andrew', lastName: 'Heaney' },
      { firstName: 'Kyle', lastName: 'Keller' },
      { firstName: 'Parker', lastName: 'Markel' },
      { firstName: 'Mike', lastName: 'Mayers' },
      { firstName: 'Keynan', lastName: 'Middleton' },
      { firstName: 'Felix', lastName: 'Pena' },
      { firstName: 'Dillon', lastName: 'Peters' },
      { firstName: 'Noe', lastName: 'Ramirez' },
      { firstName: 'Hansel', lastName: 'Robles' },
      { firstName: 'Patrick', lastName: 'Sandoval' },
      { firstName: 'Jose', lastName: 'Suarez' },
      { firstName: 'Julio', lastName: 'Teheran' },
      { firstName: 'Hector', lastName: 'Yan' },
      { firstName: 'Anthony', lastName: 'Bemboom' },
      { firstName: 'Jason', lastName: 'Castro' },
      { firstName: 'Max', lastName: 'Stassi' },
      { firstName: 'David', lastName: 'Fletcher' },
      { firstName: 'Jahmai', lastName: 'Jones' },
      { firstName: 'Tommy', lastName: 'La' },
      { firstName: 'Albert', lastName: 'Pujols' },
      { firstName: 'Anthony', lastName: 'Rendon' },
      { firstName: 'Luis', lastName: 'Rengifo' },
      { firstName: 'Andrelton', lastName: 'Simmons' },
      { firstName: 'Matt', lastName: 'Thaiss' },
      { firstName: 'Jared', lastName: 'Walsh' },
      { firstName: 'Taylor', lastName: 'Ward' },
      { firstName: 'Brian', lastName: 'Goodwin' },
      { firstName: 'Michael', lastName: 'Hermosillo' },
      { firstName: 'Mike', lastName: 'Trout' },
      { firstName: 'Justin', lastName: 'Upton' },
      { firstName: 'Shohei', lastName: 'Ohtani' }
    ]
  },
  { 
    ballPark: 'Target Field',
    id: 9,
    teamName: 'Minnesota Twins',
    website: 'twinsbaseball.com',
    urlCode: 'min',
    roster: [
      { firstName: 'Jorge', lastName: 'Alcala' },
      { firstName: 'Homer', lastName: 'Bailey' },
      { firstName: 'Jose', lastName: 'Berrios' },
      { firstName: 'Dakota', lastName: 'Chalmers' },
      { firstName: 'Tyler', lastName: 'Clippard' },
      { firstName: 'Randy', lastName: 'Dobnak' },
      { firstName: 'Tyler', lastName: 'Duffey' },
      { firstName: 'Jhoan', lastName: 'Duran' },
      { firstName: 'Brusdar', lastName: 'Graterol' },
      { firstName: 'Rich', lastName: 'Hill' },
      { firstName: 'Zack', lastName: 'Littell' },
      { firstName: 'Trevor', lastName: 'May' },
      { firstName: 'Jake', lastName: 'Odorizzi' },
      { firstName: 'Sean', lastName: 'Poppen' },
      { firstName: 'Taylor', lastName: 'Rogers' },
      { firstName: 'Fernando', lastName: 'Romero' },
      { firstName: 'Sergio', lastName: 'Romo' },
      { firstName: 'Devin', lastName: 'Smeltzer' },
      { firstName: 'Cody', lastName: 'Stashak' },
      { firstName: 'Lewis', lastName: 'Thorpe' },
      { firstName: 'Matt', lastName: 'Wisler' },
      { firstName: 'Willians', lastName: 'Astudillo' },
      { firstName: 'Alex', lastName: 'Avila' },
      { firstName: 'Mitch', lastName: 'Garver' },
      { firstName: 'Ehire', lastName: 'Adrianza' },
      { firstName: 'Luis', lastName: 'Arraez' },
      { firstName: 'Travis', lastName: 'Blankenhorn' },
      { firstName: 'Josh', lastName: 'Donaldson' },
      { firstName: 'Marwin', lastName: 'Gonzalez' },
      { firstName: 'Nick', lastName: 'Gordon' },
      { firstName: 'Jorge', lastName: 'Polanco' },
      { firstName: 'Miguel', lastName: 'Sano' },
      { firstName: 'Byron', lastName: 'Buxton' },
      { firstName: 'Jake', lastName: 'Cave' },
      { firstName: 'Gilberto', lastName: 'Celestino' },
      { firstName: 'Max', lastName: 'Kepler' },
      { firstName: 'Luke', lastName: 'Raley' },
      { firstName: 'Eddie', lastName: 'Rosario' },
      { firstName: 'LaMonte', lastName: 'Wade' },
      { firstName: 'Nelson', lastName: 'Cruz' }
    ]
  },
  { 
    ballPark: 'Yankee Stadium',
    id: 10,
    teamName: 'New York Yankees',
    website: 'yankees.com',
    urlCode: 'nyy',
    roster: [
      { firstName: 'Albert', lastName: 'Abreu' },
      { firstName: 'Zack', lastName: 'Britton' },
      { firstName: 'Luis', lastName: 'Cessa' },
      { firstName: 'Aroldis', lastName: 'Chapman' },
      { firstName: 'Gerrit', lastName: 'Cole' },
      { firstName: 'Deivi', lastName: 'Garcia' },
      { firstName: 'Luis', lastName: 'Gil' },
      { firstName: 'Chad', lastName: 'Green' },
      { firstName: 'J.A.', lastName: 'Happ' },
      { firstName: 'Ben', lastName: 'Heller' },
      { firstName: 'Jonathan', lastName: 'Holder' },
      { firstName: 'Tommy', lastName: 'Kahnle' },
      { firstName: 'Michael', lastName: 'King' },
      { firstName: 'Brooks', lastName: 'Kriske' },
      { firstName: 'Jonathan', lastName: 'Loaisiga' },
      { firstName: 'Luis', lastName: 'Medina' },
      { firstName: 'Jordan', lastName: 'Montgomery' },
      { firstName: 'Nick', lastName: 'Nelson' },
      { firstName: 'Adam', lastName: 'Ottavino' },
      { firstName: 'James', lastName: 'Paxton' },
      { firstName: 'Luis', lastName: 'Severino' },
      { firstName: 'Masahiro', lastName: 'Tanaka' },
      { firstName: 'Miguel', lastName: 'Yajure' },
      { firstName: 'Kyle', lastName: 'Higashioka' },
      { firstName: 'Gary', lastName: 'Sanchez' },
      { firstName: 'Miguel', lastName: 'Andujar' },
      { firstName: 'Thairo', lastName: 'Estrada' },
      { firstName: 'Mike', lastName: 'Ford' },
      { firstName: 'DJ', lastName: 'LeMahieu' },
      { firstName: 'Gleyber', lastName: 'Torres' },
      { firstName: 'Gio', lastName: 'Urshela' },
      { firstName: 'Luke', lastName: 'Voit' },
      { firstName: 'Tyler', lastName: 'Wade' },
      { firstName: 'Estevan', lastName: 'Florial' },
      { firstName: 'Clint', lastName: 'Frazier' },
      { firstName: 'Brett', lastName: 'Gardner' },
      { firstName: 'Aaron', lastName: 'Hicks' },
      { firstName: 'Aaron', lastName: 'Judge' },
      { firstName: 'Giancarlo', lastName: 'Stanton' },
      { firstName: 'Mike', lastName: 'Tauchman' }
    ]
  },
  { 
    ballPark: 'Oakland Coliseum',
    id: 11,
    teamName: 'Oakland Athletics',
    website: 'athletics.com',
    urlCode: 'oak',
    roster: [
      { firstName: 'Chris', lastName: 'Bassitt' },
      { firstName: 'Paul', lastName: 'Blackburn' },
      { firstName: 'Jake', lastName: 'Diekman' },
      { firstName: 'Mike', lastName: 'Fiers' },
      { firstName: 'Daniel', lastName: 'Gossett' },
      { firstName: 'Liam', lastName: 'Hendriks' },
      { firstName: 'Grant', lastName: 'Holmes' },
      { firstName: 'Daulton', lastName: 'Jefferies' },
      { firstName: 'James', lastName: 'Kaprielian' },
      { firstName: 'Jesus', lastName: 'Luzardo' },
      { firstName: 'Sean', lastName: 'Manaea' },
      { firstName: 'T.J.', lastName: 'McFarland' },
      { firstName: 'Daniel', lastName: 'Mengden' },
      { firstName: 'Frankie', lastName: 'Montas' },
      { firstName: 'Yusmeiro', lastName: 'Petit' },
      { firstName: 'A.J.', lastName: 'Puk' },
      { firstName: 'Joakim', lastName: 'Soria' },
      { firstName: 'Lou', lastName: 'Trivino' },
      { firstName: 'J.B.', lastName: 'Wendelken' },
      { firstName: 'Austin', lastName: 'Allen' },
      { firstName: 'Jonah', lastName: 'Heim' },
      { firstName: 'Sean', lastName: 'Murphy' },
      { firstName: 'Franklin', lastName: 'Barreto' },
      { firstName: 'Matt', lastName: 'Chapman' },
      { firstName: 'Vimael', lastName: 'Machin' },
      { firstName: 'Jorge', lastName: 'Mateo' },
      { firstName: 'Sheldon', lastName: 'Neuse' },
      { firstName: 'Matt', lastName: 'Olson' },
      { firstName: 'Marcus', lastName: 'Semien' },
      { firstName: 'Luis', lastName: 'Barrera' },
      { firstName: 'Skye', lastName: 'Bolt' },
      { firstName: 'Seth', lastName: 'Brown' },
      { firstName: 'Mark', lastName: 'Canha' },
      { firstName: 'Khris', lastName: 'Davis' },
      { firstName: 'Dustin', lastName: 'Fowler' },
      { firstName: 'Robbie', lastName: 'Grossman' },
      { firstName: 'Tony', lastName: 'Kemp' },
      { firstName: 'Ramon', lastName: 'Laureano' },
      { firstName: 'Chad', lastName: 'Pinder' },
      { firstName: 'Stephen', lastName: 'Piscotty' }
    ]
  },
  { 
    ballPark: 'T-Mobile Park',
    id: 12,
    teamName: 'Seattle Mariners',
    website: 'Mariners.com',
    urlCode: 'sea',
    roster: [
      { firstName: 'Austin', lastName: 'Adams' },
      { firstName: 'Dan', lastName: 'Altavilla' },
      { firstName: 'Gerson', lastName: 'Bautista' },
      { firstName: 'Brandon', lastName: 'Brennan' },
      { firstName: 'Nestor', lastName: 'Cortes' },
      { firstName: 'Justin', lastName: 'Dunn' },
      { firstName: 'Carl', lastName: 'Edwards' },
      { firstName: 'Matt', lastName: 'Festa' },
      { firstName: 'Marco', lastName: 'Gonzales' },
      { firstName: 'Kendall', lastName: 'Graveman' },
      { firstName: 'Zac', lastName: 'Grotz' },
      { firstName: 'Taylor', lastName: 'Guilbeau' },
      { firstName: 'Yusei', lastName: 'Kikuchi' },
      { firstName: 'Matt', lastName: 'Magill' },
      { firstName: 'Nick', lastName: 'Margevicius' },
      { firstName: 'Yohan', lastName: 'Ramirez' },
      { firstName: 'Ricardo', lastName: 'Sanchez' },
      { firstName: 'Justus', lastName: 'Sheffield' },
      { firstName: 'Erik', lastName: 'Swanson' },
      { firstName: 'Sam', lastName: 'Tuivailala' },
      { firstName: 'Phillips', lastName: 'Valdez' },
      { firstName: 'Art', lastName: 'Warren' },
      { firstName: 'Tom', lastName: 'Murphy' },
      { firstName: 'J.P.', lastName: 'Crawford' },
      { firstName: 'Dee', lastName: 'Gordon' },
      { firstName: 'Sam', lastName: 'Haggerty' },
      { firstName: 'Shed', lastName: 'Long' },
      { firstName: 'Tim', lastName: 'Lopes' },
      { firstName: 'Dylan', lastName: 'Moore' },
      { firstName: 'Austin', lastName: 'Nola' },
      { firstName: 'Kyle', lastName: 'Seager' },
      { firstName: 'Daniel', lastName: 'Vogelbach' },
      { firstName: 'Donnie', lastName: 'Walton' },
      { firstName: 'Evan', lastName: 'White' },
      { firstName: 'Patrick', lastName: 'Wisdom' },
      { firstName: 'Braden', lastName: 'Bishop' },
      { firstName: 'Jake', lastName: 'Fraley' },
      { firstName: 'Mitch', lastName: 'Haniger' },
      { firstName: 'Kyle', lastName: 'Lewis' },
      { firstName: 'Mallex', lastName: 'Smith' }
    ]
  },
  { 
    ballPark: 'Tropicana Field',
    id: 13,
    teamName: 'Tampa Bay Rays',
    website: 'raysbaseball.com',
    urlCode: 'tb',
    roster: [
      { firstName: 'Jose', lastName: 'Alvarado' },
      { firstName: 'Nick', lastName: 'Anderson' },
      { firstName: 'Anthony', lastName: 'Banda' },
      { firstName: 'Jalen', lastName: 'Beeks' },
      { firstName: 'Diego', lastName: 'Castillo' },
      { firstName: 'Yonny', lastName: 'Chirinos' },
      { firstName: 'Oliver', lastName: 'Drake' },
      { firstName: 'Peter', lastName: 'Fairbanks' },
      { firstName: 'Tyler', lastName: 'Glasnow' },
      { firstName: 'Brent', lastName: 'Honeywell' },
      { firstName: 'Andrew', lastName: 'Kittredge' },
      { firstName: 'Brendan', lastName: 'McKay' },
      { firstName: 'Charlie', lastName: 'Morton' },
      { firstName: 'Emilio', lastName: 'Pagan' },
      { firstName: 'Colin', lastName: 'Poche' },
      { firstName: 'Trevor', lastName: 'Richards' },
      { firstName: 'Chaz', lastName: 'Roe' },
      { firstName: 'Blake', lastName: 'Snell' },
      { firstName: 'Ryan', lastName: 'Yarbrough' },
      { firstName: 'Ronaldo', lastName: 'Hernandez' },
      { firstName: 'Michael', lastName: 'Perez' },
      { firstName: 'Mike', lastName: 'Zunino' },
      { firstName: 'Willy', lastName: 'Adames' },
      { firstName: 'Michael', lastName: 'Brosseau' },
      { firstName: 'Vidal', lastName: 'Brujan' },
      { firstName: 'Ji-Man', lastName: 'Choi' },
      { firstName: 'Yandy', lastName: 'Diaz' },
      { firstName: 'Lucius', lastName: 'Fox' },
      { firstName: 'Brandon', lastName: 'Lowe' },
      { firstName: 'Nate', lastName: 'Lowe' },
      { firstName: 'Brian', lastName: 'O\'Grady' },
      { firstName: 'Kevin', lastName: 'Padlo' },
      { firstName: 'Daniel', lastName: 'Robertson' },
      { firstName: 'Yoshitomo', lastName: 'Tsutsugo' },
      { firstName: 'Joey', lastName: 'Wendle' },
      { firstName: 'Randy', lastName: 'Arozarena' },
      { firstName: 'Kevin', lastName: 'Kiermaier' },
      { firstName: 'Jose', lastName: 'Martinez' },
      { firstName: 'Austin', lastName: 'Meadows' },
      { firstName: 'Hunter', lastName: 'Renfroe' }
    ]
  },
  { 
    ballPark: 'Globe Life Park in Arlington',
    id: 14,
    teamName: 'Texas Rangers',
    website: 'texasrangers.com',
    urlCode: 'tex',
    roster: [
      { firstName: 'Kolby', lastName: 'Allard' },
      { firstName: 'Brock', lastName: 'Burke' },
      { firstName: 'Jesse', lastName: 'Chavez' },
      { firstName: 'Kyle', lastName: 'Cody' },
      { firstName: 'Demarcus', lastName: 'Evans' },
      { firstName: 'Luke', lastName: 'Farrell' },
      { firstName: 'Kyle', lastName: 'Gibson' },
      { firstName: 'Nick', lastName: 'Goody' },
      { firstName: 'Taylor', lastName: 'Hearn' },
      { firstName: 'Jonathan', lastName: 'Hernandez' },
      { firstName: 'Ariel', lastName: 'Jurado' },
      { firstName: 'Corey', lastName: 'Kluber' },
      { firstName: 'Jose', lastName: 'Leclerc' },
      { firstName: 'Jordan', lastName: 'Lyles' },
      { firstName: 'Lance', lastName: 'Lynn' },
      { firstName: 'Brett', lastName: 'Martin' },
      { firstName: 'Yohander', lastName: 'Mendez' },
      { firstName: 'Mike', lastName: 'Minor' },
      { firstName: 'Rafael', lastName: 'Montero' },
      { firstName: 'Joe', lastName: 'Palumbo' },
      { firstName: 'Tyler', lastName: 'Phillips' },
      { firstName: 'Joely', lastName: 'Rodriguez' },
      { firstName: 'Robinson', lastName: 'Chirinos' },
      { firstName: 'Jeff', lastName: 'Mathis' },
      { firstName: 'Jose', lastName: 'Trevino' },
      { firstName: 'Elvis', lastName: 'Andrus' },
      { firstName: 'Sherten', lastName: 'Apostel' },
      { firstName: 'Todd', lastName: 'Frazier' },
      { firstName: 'Ronald', lastName: 'Guzman' },
      { firstName: 'Isiah', lastName: 'Kiner-Falefa' },
      { firstName: 'Rougned', lastName: 'Odor' },
      { firstName: 'Danny', lastName: 'Santana' },
      { firstName: 'Nick', lastName: 'Solak' },
      { firstName: 'Anderson', lastName: 'Tejeda' },
      { firstName: 'Willie', lastName: 'Calhoun' },
      { firstName: 'Shin-Soo', lastName: 'Choo' },
      { firstName: 'Joey', lastName: 'Gallo' },
      { firstName: 'Adolis', lastName: 'Garcia' },
      { firstName: 'Scott', lastName: 'Heineman' },
      { firstName: 'Leody', lastName: 'Taveras' }
    ]
  },
  { 
    ballPark: 'Rogers Centre',
    id: 15,
    teamName: 'Toronto Blue Jays',
    website: 'bluejays.com',
    urlCode: 'tor',
    roster: [
      { firstName: 'Chase', lastName: 'Anderson' },
      { firstName: 'Anthony', lastName: 'Bass' },
      { firstName: 'Ryan', lastName: 'Borucki' },
      { firstName: 'Yennsy', lastName: 'Diaz' },
      { firstName: 'Wilmer', lastName: 'Font' },
      { firstName: 'Sam', lastName: 'Gaviglio' },
      { firstName: 'Ken', lastName: 'Giles' },
      { firstName: 'Thomas', lastName: 'Hatch' },
      { firstName: 'Anthony', lastName: 'Kay' },
      { firstName: 'Elvis', lastName: 'Luciano' },
      { firstName: 'Julian', lastName: 'Merryweather' },
      { firstName: 'Patrick', lastName: 'Murphy' },
      { firstName: 'Thomas', lastName: 'Pannone' },
      { firstName: 'Hector', lastName: 'Perez' },
      { firstName: 'Sean', lastName: 'Reid-Foley' },
      { firstName: 'Tanner', lastName: 'Roark' },
      { firstName: 'Jordan', lastName: 'Romano' },
      { firstName: 'Hyun-Jin', lastName: 'Ryu' },
      { firstName: 'Matt', lastName: 'Shoemaker' },
      { firstName: 'Trent', lastName: 'Thornton' },
      { firstName: 'Jacob', lastName: 'Waguespack' },
      { firstName: 'Shun', lastName: 'Yamaguchi' },
      { firstName: 'T.J.', lastName: 'Zeuch' },
      { firstName: 'Danny', lastName: 'Jansen' },
      { firstName: 'Reese', lastName: 'McGuire' },
      { firstName: 'Bo', lastName: 'Bichette' },
      { firstName: 'Cavan', lastName: 'Biggio' },
      { firstName: 'Brandon', lastName: 'Drury' },
      { firstName: 'Santiago', lastName: 'Espinal' },
      { firstName: 'Vladimir', lastName: 'Guerrero' },
      { firstName: 'Travis', lastName: 'Shaw' },
      { firstName: 'Rowdy', lastName: 'Tellez' },
      { firstName: 'Breyvic', lastName: 'Valera' },
      { firstName: 'Anthony', lastName: 'Alford' },
      { firstName: 'Jonathan', lastName: 'Davis' },
      { firstName: 'Derek', lastName: 'Fisher' },
      { firstName: 'Randal', lastName: 'Grichuk' },
      { firstName: 'Lourdes', lastName: 'Gurriel' },
      { firstName: 'Teoscar', lastName: 'Hernandez' },
      { firstName: 'Billy', lastName: 'McKinney' }
    ]
  },
  { 
    ballPark: 'Chase Field',
    id: 16,
    teamName: 'Arizona Diamondbacks',
    website: 'dbacks.com',
    urlCode: 'ari',
    roster: [
      { firstName: 'Silvino', lastName: 'Bracho' },
      { firstName: 'Archie', lastName: 'Bradley' },
      { firstName: 'Madison', lastName: 'Bumgarner' },
      { firstName: 'Andrew', lastName: 'Chafin' },
      { firstName: 'Taylor', lastName: 'Clarke' },
      { firstName: 'Stefan', lastName: 'Crichton' },
      { firstName: 'Jon', lastName: 'Duplantier' },
      { firstName: 'Zac', lastName: 'Gallen' },
      { firstName: 'Kevin', lastName: 'Ginkel' },
      { firstName: 'Junior', lastName: 'Guerra' },
      { firstName: 'Merrill', lastName: 'Kelly' },
      { firstName: 'Mike', lastName: 'Leake' },
      { firstName: 'Yoan', lastName: 'Lopez' },
      { firstName: 'Corbin', lastName: 'Martin' },
      { firstName: 'Joel', lastName: 'Payamps' },
      { firstName: 'Robbie', lastName: 'Ray' },
      { firstName: 'Hector', lastName: 'Rondon' },
      { firstName: 'Riley', lastName: 'Smith' },
      { firstName: 'Bo', lastName: 'Takahashi' },
      { firstName: 'Emilio', lastName: 'Vargas' },
      { firstName: 'Luke', lastName: 'Weaver' },
      { firstName: 'Taylor', lastName: 'Widener' },
      { firstName: 'Alex', lastName: 'Young' },
      { firstName: 'Carson', lastName: 'Kelly' },
      { firstName: 'Stephen', lastName: 'Vogt' },
      { firstName: 'Nick', lastName: 'Ahmed' },
      { firstName: 'Kevin', lastName: 'Cron' },
      { firstName: 'Eduardo', lastName: 'Escobar' },
      { firstName: 'Jake', lastName: 'Lamb' },
      { firstName: 'Domingo', lastName: 'Leyba' },
      { firstName: 'Wyatt', lastName: 'Mathisen' },
      { firstName: 'Josh', lastName: 'Rojas' },
      { firstName: 'Ildemaro', lastName: 'Vargas' },
      { firstName: 'Christian', lastName: 'Walker' },
      { firstName: 'Andy', lastName: 'Young' },
      { firstName: 'Kole', lastName: 'Calhoun' },
      { firstName: 'Tim', lastName: 'Locastro' },
      { firstName: 'Ketel', lastName: 'Marte' },
      { firstName: 'Starling', lastName: 'Marte' },
      { firstName: 'David', lastName: 'Peralta' }
    ]
  },
  { 
    ballPark: 'Truist Park',
    id: 17,
    teamName: 'Atlanta Braves',
    website: 'braves.com',
    urlCode: 'atl',
    roster: [
      { firstName: 'Tucker', lastName: 'Davidson' },
      { firstName: 'Grant', lastName: 'Dayton' },
      { firstName: 'Jasseel', lastName: 'De' },
      { firstName: 'Mike', lastName: 'Foltynewicz' },
      { firstName: 'Max', lastName: 'Fried' },
      { firstName: 'Shane', lastName: 'Greene' },
      { firstName: 'Cole', lastName: 'Hamels' },
      { firstName: 'Luke', lastName: 'Jackson' },
      { firstName: 'Chris', lastName: 'Martin' },
      { firstName: 'Mark', lastName: 'Melancon' },
      { firstName: 'A.J.', lastName: 'Minter' },
      { firstName: 'Sean', lastName: 'Newcomb' },
      { firstName: 'Darren', lastName: 'O\'Day' },
      { firstName: 'Philip', lastName: 'Pfeifer' },
      { firstName: 'Will', lastName: 'Smith' },
      { firstName: 'Chad', lastName: 'Sobotka' },
      { firstName: 'Mike', lastName: 'Soroka' },
      { firstName: 'Touki', lastName: 'Toussaint' },
      { firstName: 'Jeremy', lastName: 'Walker' },
      { firstName: 'Jacob', lastName: 'Webb' },
      { firstName: 'Patrick', lastName: 'Weigel' },
      { firstName: 'Bryse', lastName: 'Wilson' },
      { firstName: 'Kyle', lastName: 'Wright' },
      { firstName: 'Huascar', lastName: 'Ynoa' },
      { firstName: 'William', lastName: 'Contreras' },
      { firstName: 'Travis', lastName: 'd\'Arnaud' },
      { firstName: 'Tyler', lastName: 'Flowers' },
      { firstName: 'Alex', lastName: 'Jackson' },
      { firstName: 'Ozzie', lastName: 'Albies' },
      { firstName: 'Johan', lastName: 'Camargo' },
      { firstName: 'Freddie', lastName: 'Freeman' },
      { firstName: 'Adeiny', lastName: 'Hechavarria' },
      { firstName: 'Dansby', lastName: 'Swanson' },
      { firstName: 'Ronald', lastName: 'Acuna' },
      { firstName: 'Adam', lastName: 'Duvall' },
      { firstName: 'Ender', lastName: 'Inciarte' },
      { firstName: 'Nick', lastName: 'Markakis' },
      { firstName: 'Marcell', lastName: 'Ozuna' },
      { firstName: 'Cristian', lastName: 'Pache' },
      { firstName: 'Austin', lastName: 'Riley' }
    ]
  },
  { 
    ballPark: 'Wrigley Field',
    id: 18,
    teamName: 'Chicago Cubs',
    website: 'cubs.com',
    urlCode: 'chc',
    roster: [
      { firstName: 'Adbert', lastName: 'Alzolay' },
      { firstName: 'Tyler', lastName: 'Chatwood' },
      { firstName: 'Jharel', lastName: 'Cotton' },
      { firstName: 'Yu', lastName: 'Darvish' },
      { firstName: 'Kyle', lastName: 'Hendricks' },
      { firstName: 'Craig', lastName: 'Kimbrel' },
      { firstName: 'Travis', lastName: 'Lakins' },
      { firstName: 'Jon', lastName: 'Lester' },
      { firstName: 'Dillon', lastName: 'Maples' },
      { firstName: 'Trevor', lastName: 'Megill' },
      { firstName: 'Tyson', lastName: 'Miller' },
      { firstName: 'Alec', lastName: 'Mills' },
      { firstName: 'James', lastName: 'Norwood' },
      { firstName: 'Jose', lastName: 'Quintana' },
      { firstName: 'Colin', lastName: 'Rea' },
      { firstName: 'Manuel', lastName: 'Rodriguez' },
      { firstName: 'Kyle', lastName: 'Ryan' },
      { firstName: 'Casey', lastName: 'Sadler' },
      { firstName: 'Justin', lastName: 'Steele' },
      { firstName: 'Ryan', lastName: 'Tepera' },
      { firstName: 'Duane', lastName: 'Underwood' },
      { firstName: 'Rowan', lastName: 'Wick' },
      { firstName: 'Brad', lastName: 'Wieck' },
      { firstName: 'Dan', lastName: 'Winkler' },
      { firstName: 'Miguel', lastName: 'Amaya' },
      { firstName: 'Victor', lastName: 'Caratini' },
      { firstName: 'Willson', lastName: 'Contreras' },
      { firstName: 'Javier', lastName: 'Baez' },
      { firstName: 'David', lastName: 'Bote' },
      { firstName: 'Kris', lastName: 'Bryant' },
      { firstName: 'Daniel', lastName: 'Descalso' },
      { firstName: 'Robel', lastName: 'Garcia' },
      { firstName: 'Nico', lastName: 'Hoerner' },
      { firstName: 'Anthony', lastName: 'Rizzo' },
      { firstName: 'Zack', lastName: 'Short' },
      { firstName: 'Albert', lastName: 'Almora' },
      { firstName: 'Ian', lastName: 'Happ' },
      { firstName: 'Jason', lastName: 'Heyward' },
      { firstName: 'Kyle', lastName: 'Schwarber' },
      { firstName: 'Steven', lastName: 'Souza' }
    ]
  },
  { 
    ballPark: 'Great American Ball Park',
    id: 19,
    teamName: 'Cincinnati Reds',
    website: 'reds.com',
    urlCode: 'cin',
    roster: [
      { firstName: 'Tejay', lastName: 'Antone' },
      { firstName: 'Trevor', lastName: 'Bauer' },
      { firstName: 'Matt', lastName: 'Bowman' },
      { firstName: 'Luis', lastName: 'Castillo' },
      { firstName: 'Jose', lastName: 'De' },
      { firstName: 'Anthony', lastName: 'DeSclafani' },
      { firstName: 'Amir', lastName: 'Garrett' },
      { firstName: 'Sonny', lastName: 'Gray' },
      { firstName: 'Ryan', lastName: 'Hendrix' },
      { firstName: 'Raisel', lastName: 'Iglesias' },
      { firstName: 'Joel', lastName: 'Kuhnel' },
      { firstName: 'Michael', lastName: 'Lorenzen' },
      { firstName: 'Tyler', lastName: 'Mahle' },
      { firstName: 'Wade', lastName: 'Miley' },
      { firstName: 'Cody', lastName: 'Reed' },
      { firstName: 'Sal', lastName: 'Romano' },
      { firstName: 'Tony', lastName: 'Santillan' },
      { firstName: 'Justin', lastName: 'Shafer' },
      { firstName: 'Lucas', lastName: 'Sims' },
      { firstName: 'Josh', lastName: 'D.' },
      { firstName: 'Robert', lastName: 'Stephenson' },
      { firstName: 'Tucker', lastName: 'Barnhart' },
      { firstName: 'Curt', lastName: 'Casali' },
      { firstName: 'Tyler', lastName: 'Stephenson' },
      { firstName: 'Alex', lastName: 'Blandino' },
      { firstName: 'Kyle', lastName: 'Farmer' },
      { firstName: 'Freddy', lastName: 'Galvis' },
      { firstName: 'Mike', lastName: 'Moustakas' },
      { firstName: 'Eugenio', lastName: 'Suarez' },
      { firstName: 'Joey', lastName: 'Votto' },
      { firstName: 'Shogo', lastName: 'Akiyama' },
      { firstName: 'Aristides', lastName: 'Aquino' },
      { firstName: 'Nick', lastName: 'Castellanos' },
      { firstName: 'Phillip', lastName: 'Ervin' },
      { firstName: 'Travis', lastName: 'Jankowski' },
      { firstName: 'Mark', lastName: 'Payton' },
      { firstName: 'Scott', lastName: 'Schebler' },
      { firstName: 'Nick', lastName: 'Senzel' },
      { firstName: 'Josh', lastName: 'VanMeter' },
      { firstName: 'Jesse', lastName: 'Winker' }
    ]
  },
  { 
    ballPark: 'Coors Field',
    id: 20,
    teamName: 'Colorado Rockies',
    website: 'Rockies.com',
    urlCode: 'col',
    roster: [
      { firstName: 'Yency', lastName: 'Almonte' },
      { firstName: 'Ben', lastName: 'Bowden' },
      { firstName: 'Ryan', lastName: 'Castellani' },
      { firstName: 'Wade', lastName: 'Davis' },
      { firstName: 'Jairo', lastName: 'Diaz' },
      { firstName: 'Phillip', lastName: 'Diehl' },
      { firstName: 'Carlos', lastName: 'Estevez' },
      { firstName: 'Kyle', lastName: 'Freeland' },
      { firstName: 'Chi', lastName: 'Chi' },
      { firstName: 'Ashton', lastName: 'Goudeau' },
      { firstName: 'Jon', lastName: 'Gray' },
      { firstName: 'Jeff', lastName: 'Hoffman' },
      { firstName: 'Tyler', lastName: 'Kinley' },
      { firstName: 'Peter', lastName: 'Lambert' },
      { firstName: 'German', lastName: 'Marquez' },
      { firstName: 'Jake', lastName: 'McGee' },
      { firstName: 'Jose', lastName: 'Mujica' },
      { firstName: 'Scott', lastName: 'Oberg' },
      { firstName: 'James', lastName: 'Pazos' },
      { firstName: 'Antonio', lastName: 'Santos' },
      { firstName: 'Antonio', lastName: 'Senzatela' },
      { firstName: 'Bryan', lastName: 'Shaw' },
      { firstName: 'Jesus', lastName: 'Tinoco' },
      { firstName: 'Dom', lastName: 'Nunez' },
      { firstName: 'Tony', lastName: 'Wolters' },
      { firstName: 'Nolan', lastName: 'Arenado' },
      { firstName: 'Josh', lastName: 'Fuentes' },
      { firstName: 'Garrett', lastName: 'Hampson' },
      { firstName: 'Ryan', lastName: 'McMahon' },
      { firstName: 'Daniel', lastName: 'Murphy' },
      { firstName: 'Tyler', lastName: 'Nevin' },
      { firstName: 'Brendan', lastName: 'Rodgers' },
      { firstName: 'Trevor', lastName: 'Story' },
      { firstName: 'Charlie', lastName: 'Blackmon' },
      { firstName: 'David', lastName: 'Dahl' },
      { firstName: 'Yonathan', lastName: 'Daza' },
      { firstName: 'Ian', lastName: 'Desmond' },
      { firstName: 'Sam', lastName: 'Hilliard' },
      { firstName: 'Raimel', lastName: 'Tapia' }
    ]
  },
  { 
    ballPark: 'Dodger Stadium',
    id: 21,
    teamName: 'Los Angeles Dodgers',
    website: 'dodgers.com',
    urlCode: 'la',
    roster: [
      { firstName: 'Scott', lastName: 'Alexander' },
      { firstName: 'Pedro', lastName: 'Baez' },
      { firstName: 'Walker', lastName: 'Buehler' },
      { firstName: 'Caleb', lastName: 'Ferguson' },
      { firstName: 'Dylan', lastName: 'Floro' },
      { firstName: 'Tony', lastName: 'Gonsolin' },
      { firstName: 'Victor', lastName: 'Gonzalez' },
      { firstName: 'Kenley', lastName: 'Jansen' },
      { firstName: 'Joe', lastName: 'Kelly' },
      { firstName: 'Clayton', lastName: 'Kershaw' },
      { firstName: 'Adam', lastName: 'Kolarek' },
      { firstName: 'Kenta', lastName: 'Maeda' },
      { firstName: 'Dustin', lastName: 'May' },
      { firstName: 'Jimmy', lastName: 'Nelson' },
      { firstName: 'Dennis', lastName: 'Santana' },
      { firstName: 'Josh', lastName: 'Sborz' },
      { firstName: 'Ross', lastName: 'Stripling' },
      { firstName: 'Blake', lastName: 'Treinen' },
      { firstName: 'Julio', lastName: 'Urias' },
      { firstName: 'Mitchell', lastName: 'White' },
      { firstName: 'Alex', lastName: 'Wood' },
      { firstName: 'Austin', lastName: 'Barnes' },
      { firstName: 'Keibert', lastName: 'Ruiz' },
      { firstName: 'Will', lastName: 'Smith' },
      { firstName: 'Matt', lastName: 'Beaty' },
      { firstName: 'Enrique', lastName: 'Hernandez' },
      { firstName: 'Gavin', lastName: 'Lux' },
      { firstName: 'Zach', lastName: 'McKinstry' },
      { firstName: 'Max', lastName: 'Muncy' },
      { firstName: 'Edwin', lastName: 'Rios' },
      { firstName: 'Corey', lastName: 'Seager' },
      { firstName: 'Justin', lastName: 'Turner' },
      { firstName: 'Tyler', lastName: 'White' },
      { firstName: 'Cody', lastName: 'Bellinger' },
      { firstName: 'Kyle', lastName: 'Garlick' },
      { firstName: 'Joc', lastName: 'Pederson' },
      { firstName: 'DJ', lastName: 'Peters' },
      { firstName: 'A.J.', lastName: 'Pollock' },
      { firstName: 'Chris', lastName: 'Taylor' },
      { firstName: 'Alex', lastName: 'Verdugo' }
    ]
  },
  { ballPark: 'Miller Park',
    id: 22,
    teamName: 'Milwaukee Brewers',
    website: 'brewers.com',
    urlCode: 'mil',
    roster: [
      { firstName: 'Brett', lastName: 'Anderson' },
      { firstName: 'Ray', lastName: 'Black' },
      { firstName: 'Corbin', lastName: 'Burnes' },
      { firstName: 'Alex', lastName: 'Claudio' },
      { firstName: 'J.P.', lastName: 'Feyereisen' },
      { firstName: 'Deolis', lastName: 'Guerra' },
      { firstName: 'Josh', lastName: 'Hader' },
      { firstName: 'Adrian', lastName: 'Houser' },
      { firstName: 'Corey', lastName: 'Knebel' },
      { firstName: 'Eric', lastName: 'Lauer' },
      { firstName: 'Josh', lastName: 'Lindblom' },
      { firstName: 'Freddy', lastName: 'Peralta' },
      { firstName: 'Angel', lastName: 'Perdomo' },
      { firstName: 'Trey', lastName: 'Supak' },
      { firstName: 'Brent', lastName: 'Suter' },
      { firstName: 'Bobby', lastName: 'Wahl' },
      { firstName: 'Devin', lastName: 'Williams' },
      { firstName: 'Taylor', lastName: 'Williams' },
      { firstName: 'Brandon', lastName: 'Woodruff' },
      { firstName: 'Eric', lastName: 'Yardley' },
      { firstName: 'David', lastName: 'Freitas' },
      { firstName: 'Omar', lastName: 'Narvaez' },
      { firstName: 'Jacob', lastName: 'Nottingham' },
      { firstName: 'Manny', lastName: 'Pina' },
      { firstName: 'Orlando', lastName: 'Arcia' },
      { firstName: 'Jedd', lastName: 'Gyorko' },
      { firstName: 'Ryon', lastName: 'Healy' },
      { firstName: 'Keston', lastName: 'Hiura' },
      { firstName: 'Mark', lastName: 'Mathias' },
      { firstName: 'Ronny', lastName: 'Rodriguez' },
      { firstName: 'Justin', lastName: 'Smoak' },
      { firstName: 'Eric', lastName: 'Sogard' },
      { firstName: 'Luis', lastName: 'Urias' },
      { firstName: 'Ryan', lastName: 'Braun' },
      { firstName: 'Lorenzo', lastName: 'Cain' },
      { firstName: 'Ben', lastName: 'Gamel' },
      { firstName: 'Avisail', lastName: 'Garcia' },
      { firstName: 'Corey', lastName: 'Ray' },
      { firstName: 'Tyrone', lastName: 'Taylor' },
      { firstName: 'Christian', lastName: 'Yelich' }
    ]
  },
  { 
    ballPark: 'Citi Field',
    id: 23,
    teamName: 'New York Mets',
    website: 'mets.com',
    urlCode: 'nym',
    roster: [
      { firstName: 'Tyler', lastName: 'Bashlor' },
      { firstName: 'Dellin', lastName: 'Betances' },
      { firstName: 'Brad', lastName: 'Brach' },
      { firstName: 'Jacob', lastName: 'deGrom' },
      { firstName: 'Edwin', lastName: 'Diaz' },
      { firstName: 'Jeurys', lastName: 'Familia' },
      { firstName: 'Stephen', lastName: 'Gonsalves' },
      { firstName: 'Robert', lastName: 'Gsellman' },
      { firstName: 'Jordan', lastName: 'Humphreys' },
      { firstName: 'Franklyn', lastName: 'Kilome' },
      { firstName: 'Walker', lastName: 'Lockett' },
      { firstName: 'Seth', lastName: 'Lugo' },
      { firstName: 'Steven', lastName: 'Matz' },
      { firstName: 'Corey', lastName: 'Oswalt' },
      { firstName: 'Rick', lastName: 'Porcello' },
      { firstName: 'Jacob', lastName: 'Rhame' },
      { firstName: 'Paul', lastName: 'Sewald' },
      { firstName: 'Drew', lastName: 'Smith' },
      { firstName: 'Marcus', lastName: 'Stroman' },
      { firstName: 'Noah', lastName: 'Syndergaard' },
      { firstName: 'Thomas', lastName: 'Szapucki' },
      { firstName: 'Michael', lastName: 'Wacha' },
      { firstName: 'Justin', lastName: 'Wilson' },
      { firstName: 'Daniel', lastName: 'Zamora' },
      { firstName: 'Tomas', lastName: 'Nido' },
      { firstName: 'Wilson', lastName: 'Ramos' },
      { firstName: 'Ali', lastName: 'Sanchez' },
      { firstName: 'Pete', lastName: 'Alonso' },
      { firstName: 'Robinson', lastName: 'Cano' },
      { firstName: 'J.D.', lastName: 'Davis' },
      { firstName: 'Andres', lastName: 'Gimenez' },
      { firstName: 'Luis', lastName: 'Guillorme' },
      { firstName: 'Jed', lastName: 'Lowrie' },
      { firstName: 'Amed', lastName: 'Rosario' },
      { firstName: 'Dominic', lastName: 'Smith' },
      { firstName: 'Yoenis', lastName: 'Cespedes' },
      { firstName: 'Michael', lastName: 'Conforto' },
      { firstName: 'Jake', lastName: 'Marisnick' },
      { firstName: 'Jeff', lastName: 'McNeil' },
      { firstName: 'Brandon', lastName: 'Nimmo' }
    ]
  },
  { 
    ballPark: 'Citizens Bank Park',
    id: 24,
    teamName: 'Philadelphia Phillies',
    website: 'phillies.com',
    urlCode: 'phi',
    roster: [
      { firstName: 'Jose', lastName: 'Alvarez' },
      { firstName: 'Victor', lastName: 'Arano' },
      { firstName: 'Jake', lastName: 'Arrieta' },
      { firstName: 'Garrett', lastName: 'Cleavinger' },
      { firstName: 'Austin', lastName: 'Davis' },
      { firstName: 'Enyel', lastName: 'De' },
      { firstName: 'Seranthony', lastName: 'Dominguez' },
      { firstName: 'Zach', lastName: 'Eflin' },
      { firstName: 'Edgar', lastName: 'Garcia' },
      { firstName: 'JD', lastName: 'Hammer' },
      { firstName: 'Cole', lastName: 'Irvin' },
      { firstName: 'Trevor', lastName: 'Kelley' },
      { firstName: 'Mauricio', lastName: 'Llovera' },
      { firstName: 'Adonis', lastName: 'Medina' },
      { firstName: 'Adam', lastName: 'Morgan' },
      { firstName: 'Hector', lastName: 'Neris' },
      { firstName: 'Aaron', lastName: 'Nola' },
      { firstName: 'Nick', lastName: 'Pivetta' },
      { firstName: 'David', lastName: 'Robertson' },
      { firstName: 'JoJo', lastName: 'Romero' },
      { firstName: 'Cristopher', lastName: 'Sanchez' },
      { firstName: 'Robert', lastName: 'Stock' },
      { firstName: 'Ranger', lastName: 'Suarez' },
      { firstName: 'Vince', lastName: 'Velasquez' },
      { firstName: 'Zack', lastName: 'Wheeler' },
      { firstName: 'Deivy', lastName: 'Grullon' },
      { firstName: 'Andrew', lastName: 'Knapp' },
      { firstName: 'J.T.', lastName: 'Realmuto' },
      { firstName: 'Arquimedes', lastName: 'Gamboa' },
      { firstName: 'Didi', lastName: 'Gregorius' },
      { firstName: 'Rhys', lastName: 'Hoskins' },
      { firstName: 'Scott', lastName: 'Kingery' },
      { firstName: 'Jean', lastName: 'Segura' },
      { firstName: 'Jay', lastName: 'Bruce' },
      { firstName: 'Bryce', lastName: 'Harper' },
      { firstName: 'Adam', lastName: 'Haseley' },
      { firstName: 'Nick', lastName: 'Martini' },
      { firstName: 'Andrew', lastName: 'McCutchen' },
      { firstName: 'Roman', lastName: 'Quinn' },
      { firstName: 'Nick', lastName: 'Williams' }
    ]
  },
  { 
    ballPark: 'PNC Park',
    id: 25,
    teamName: 'Pittsburgh Pirates',
    website: 'pirates.com',
    urlCode: 'pit',
    roster: [
      { firstName: 'Chris', lastName: 'Archer' },
      { firstName: 'Steven', lastName: 'Brault' },
      { firstName: 'JT', lastName: 'Brubaker' },
      { firstName: 'Nick', lastName: 'Burdi' },
      { firstName: 'Blake', lastName: 'Cederlind' },
      { firstName: 'Kyle', lastName: 'Crick' },
      { firstName: 'Michael', lastName: 'Feliz' },
      { firstName: 'Geoff', lastName: 'Hartlieb' },
      { firstName: 'Clay', lastName: 'Holmes' },
      { firstName: 'Sam', lastName: 'Howard' },
      { firstName: 'Keone', lastName: 'Kela' },
      { firstName: 'Mitch', lastName: 'Keller' },
      { firstName: 'Chad', lastName: 'Kuhl' },
      { firstName: 'Joe', lastName: 'Musgrove' },
      { firstName: 'Dovydas', lastName: 'Neverauskas' },
      { firstName: 'Cody', lastName: 'Ponce' },
      { firstName: 'Yacksel', lastName: 'Rios' },
      { firstName: 'Richard', lastName: 'Rodriguez' },
      { firstName: 'Edgar', lastName: 'Santana' },
      { firstName: 'Chris', lastName: 'Stratton' },
      { firstName: 'Jameson', lastName: 'Taillon' },
      { firstName: 'Trevor', lastName: 'Williams' },
      { firstName: 'Luke', lastName: 'Maile' },
      { firstName: 'Jacob', lastName: 'Stallings' },
      { firstName: 'Josh', lastName: 'Bell' },
      { firstName: 'Will', lastName: 'Craig' },
      { firstName: 'Oneil', lastName: 'Cruz' },
      { firstName: 'Adam', lastName: 'Frazier' },
      { firstName: 'Erik', lastName: 'Gonzalez' },
      { firstName: 'Ke\'Bryan', lastName: 'Hayes' },
      { firstName: 'Colin', lastName: 'Moran' },
      { firstName: 'Kevin', lastName: 'Newman' },
      { firstName: 'Jose', lastName: 'Osuna' },
      { firstName: 'Cole', lastName: 'Tucker' },
      { firstName: 'Guillermo', lastName: 'Heredia' },
      { firstName: 'Kevin', lastName: 'Kramer' },
      { firstName: 'Jason', lastName: 'Martin' },
      { firstName: 'Gregory', lastName: 'Polanco' },
      { firstName: 'Bryan', lastName: 'Reynolds' }
    ]
  },
  { 
    ballPark: 'Petco Park',
    id: 26,
    teamName: 'San Diego Padres',
    website: 'padres.com',
    urlCode: 'sd',
    roster: [
      { firstName: 'Michel', lastName: 'Baez' },
      { firstName: 'David', lastName: 'Bednar' },
      { firstName: 'Ronald', lastName: 'Bolanos' },
      { firstName: 'Jose', lastName: 'Castillo' },
      { firstName: 'Zach', lastName: 'Davies' },
      { firstName: 'Anderson', lastName: 'Espinoza' },
      { firstName: 'Javy', lastName: 'Guerra' },
      { firstName: 'Pierce', lastName: 'Johnson' },
      { firstName: 'Dinelson', lastName: 'Lamet' },
      { firstName: 'Joey', lastName: 'Lucchesi' },
      { firstName: 'Adrian', lastName: 'Morejon' },
      { firstName: 'Andres', lastName: 'Munoz' },
      { firstName: 'Chris', lastName: 'Paddack' },
      { firstName: 'Luis', lastName: 'Perdomo' },
      { firstName: 'Drew', lastName: 'Pomeranz' },
      { firstName: 'Cal', lastName: 'Quantrill' },
      { firstName: 'Gerardo', lastName: 'Reyes' },
      { firstName: 'Garrett', lastName: 'Richards' },
      { firstName: 'Craig', lastName: 'Stammen' },
      { firstName: 'Matt', lastName: 'Strahm' },
      { firstName: 'Trey', lastName: 'Wingenter' },
      { firstName: 'Kirby', lastName: 'Yates' },
      { firstName: 'Austin', lastName: 'Hedges' },
      { firstName: 'Francisco', lastName: 'Mejia' },
      { firstName: 'Luis', lastName: 'Torrens' },
      { firstName: 'Jake', lastName: 'Cronenworth' },
      { firstName: 'Ty', lastName: 'France' },
      { firstName: 'Greg', lastName: 'Garcia' },
      { firstName: 'Eric', lastName: 'Hosmer' },
      { firstName: 'Manny', lastName: 'Machado' },
      { firstName: 'Jurickson', lastName: 'Profar' },
      { firstName: 'Fernando', lastName: 'Tatis' },
      { firstName: 'Franchy', lastName: 'Cordero' },
      { firstName: 'Trent', lastName: 'Grisham' },
      { firstName: 'Manuel', lastName: 'Margot' },
      { firstName: 'Wil', lastName: 'Myers' },
      { firstName: 'Josh', lastName: 'Naylor' },
      { firstName: 'Edward', lastName: 'Olivares' },
      { firstName: 'Jorge', lastName: 'Ona' },
      { firstName: 'Tommy', lastName: 'Pham' }
    ]
  },
  { 
    ballPark: 'Oracle Park',
    id: 27,
    teamName: 'San Francisco Giants',
    website: 'SFGiants.com',
    urlCode: 'sf',
    roster: [
      { firstName: 'Melvin', lastName: 'Adon' },
      { firstName: 'Shaun', lastName: 'Anderson' },
      { firstName: 'Tyler', lastName: 'Anderson' },
      { firstName: 'Tyler', lastName: 'Beede' },
      { firstName: 'Sam', lastName: 'Coonrod' },
      { firstName: 'Johnny', lastName: 'Cueto' },
      { firstName: 'Enderson', lastName: 'Franco' },
      { firstName: 'Kevin', lastName: 'Gausman' },
      { firstName: 'Trevor', lastName: 'Gott' },
      { firstName: 'Jandel', lastName: 'Gustave' },
      { firstName: 'Dany', lastName: 'Jimenez' },
      { firstName: 'Luis', lastName: 'Madero' },
      { firstName: 'Conner', lastName: 'Menez' },
      { firstName: 'Reyes', lastName: 'Moronta' },
      { firstName: 'Wandy', lastName: 'Peralta' },
      { firstName: 'Dereck', lastName: 'Rodriguez' },
      { firstName: 'Tyler', lastName: 'Rogers' },
      { firstName: 'Jeff', lastName: 'Samardzija' },
      { firstName: 'Sam', lastName: 'Selman' },
      { firstName: 'Burch', lastName: 'Smith' },
      { firstName: 'Drew', lastName: 'Smyly' },
      { firstName: 'Andrew', lastName: 'Suarez' },
      { firstName: 'Tony', lastName: 'Watson' },
      { firstName: 'Logan', lastName: 'Webb' },
      { firstName: 'Aramis', lastName: 'Garcia' },
      { firstName: 'Buster', lastName: 'Posey' },
      { firstName: 'Abiatal', lastName: 'Avelino' },
      { firstName: 'Brandon', lastName: 'Belt' },
      { firstName: 'Brandon', lastName: 'Crawford' },
      { firstName: 'Mauricio', lastName: 'Dubon' },
      { firstName: 'Evan', lastName: 'Longoria' },
      { firstName: 'Donovan', lastName: 'Solano' },
      { firstName: 'Kean', lastName: 'Wong' },
      { firstName: 'Jaylin', lastName: 'Davis' },
      { firstName: 'Alex', lastName: 'Dickerson' },
      { firstName: 'Steven', lastName: 'Duggar' },
      { firstName: 'Joe', lastName: 'McCarthy' },
      { firstName: 'Chris', lastName: 'Shaw' },
      { firstName: 'Austin', lastName: 'Slater' },
      { firstName: 'Mike', lastName: 'Yastrzemski' }
    ]
  },
  { 
    ballPark: 'Busch Stadium',
    id: 28,
    teamName: 'St. Louis Cardinals',
    website: 'cardinals.com',
    urlCode: 'stl',
    roster: [
      { firstName: 'John', lastName: 'Brebbia' },
      { firstName: 'Genesis', lastName: 'Cabrera' },
      { firstName: 'Brett', lastName: 'Cecil' },
      { firstName: 'Junior', lastName: 'Fernandez' },
      { firstName: 'Jack', lastName: 'Flaherty' },
      { firstName: 'Giovanny', lastName: 'Gallegos' },
      { firstName: 'John', lastName: 'Gant' },
      { firstName: 'Austin', lastName: 'Gomber' },
      { firstName: 'Ryan', lastName: 'Helsley' },
      { firstName: 'Jordan', lastName: 'Hicks' },
      { firstName: 'Dakota', lastName: 'Hudson' },
      { firstName: 'Kwang-Hyun', lastName: 'Kim' },
      { firstName: 'Carlos', lastName: 'Martinez' },
      { firstName: 'Miles', lastName: 'Mikolas' },
      { firstName: 'Andrew', lastName: 'Miller' },
      { firstName: 'Daniel', lastName: 'Ponce' },
      { firstName: 'Alex', lastName: 'Reyes' },
      { firstName: 'Alvaro', lastName: 'Seijas' },
      { firstName: 'Adam', lastName: 'Wainwright' },
      { firstName: 'Tyler', lastName: 'Webb' },
      { firstName: 'Jake', lastName: 'Woodford' },
      { firstName: 'Andrew', lastName: 'Knizner' },
      { firstName: 'Yadier', lastName: 'Molina' },
      { firstName: 'Matt', lastName: 'Wieters' },
      { firstName: 'Matt', lastName: 'Carpenter' },
      { firstName: 'Paul', lastName: 'DeJong' },
      { firstName: 'Tommy', lastName: 'Edman' },
      { firstName: 'Paul', lastName: 'Goldschmidt' },
      { firstName: 'Elehuris', lastName: 'Montero' },
      { firstName: 'Yairo', lastName: 'Munoz' },
      { firstName: 'Rangel', lastName: 'Ravelo' },
      { firstName: 'Edmundo', lastName: 'Sosa' },
      { firstName: 'Ramon', lastName: 'Urias' },
      { firstName: 'Kolten', lastName: 'Wong' },
      { firstName: 'Harrison', lastName: 'Bader' },
      { firstName: 'Austin', lastName: 'Dean' },
      { firstName: 'Dexter', lastName: 'Fowler' },
      { firstName: 'Tyler', lastName: 'O\'Neill' },
      { firstName: 'Lane', lastName: 'Thomas' },
      { firstName: 'Justin', lastName: 'Williams' }
    ]
  },
  { 
    ballPark: 'Nationals Park',
    id: 29,
    teamName: 'Washington Nationals',
    website: 'nationals.com',
    urlCode: 'was',
    roster: [
      { firstName: 'Aaron', lastName: 'Barrett' },
      { firstName: 'James', lastName: 'Bourque' },
      { firstName: 'Ben', lastName: 'Braymer' },
      { firstName: 'Patrick', lastName: 'Corbin' },
      { firstName: 'Sean', lastName: 'Doolittle' },
      { firstName: 'Roenis', lastName: 'Elias' },
      { firstName: 'Erick', lastName: 'Fedde' },
      { firstName: 'Kyle', lastName: 'Finnegan' },
      { firstName: 'Ryne', lastName: 'Harper' },
      { firstName: 'Will', lastName: 'Harris' },
      { firstName: 'Daniel', lastName: 'Hudson' },
      { firstName: 'Kyle', lastName: 'McGowin' },
      { firstName: 'Tanner', lastName: 'Rainey' },
      { firstName: 'Joe', lastName: 'Ross' },
      { firstName: 'Anibal', lastName: 'Sanchez' },
      { firstName: 'Max', lastName: 'Scherzer' },
      { firstName: 'Stephen', lastName: 'Strasburg' },
      { firstName: 'Hunter', lastName: 'Strickland' },
      { firstName: 'Wander', lastName: 'Suero' },
      { firstName: 'Austin', lastName: 'Voth' },
      { firstName: 'Austen', lastName: 'Williams' },
      { firstName: 'Tres', lastName: 'Barrera' },
      { firstName: 'Yan', lastName: 'Gomes' },
      { firstName: 'Raudy', lastName: 'Read' },
      { firstName: 'Kurt', lastName: 'Suzuki' },
      { firstName: 'Asdrubal', lastName: 'Cabrera' },
      { firstName: 'Starlin', lastName: 'Castro' },
      { firstName: 'Wilmer', lastName: 'Difo' },
      { firstName: 'Howie', lastName: 'Kendrick' },
      { firstName: 'Carter', lastName: 'Kieboom' },
      { firstName: 'Jake', lastName: 'Noll' },
      { firstName: 'Adrian', lastName: 'Sanchez' },
      { firstName: 'Eric', lastName: 'Thames' },
      { firstName: 'Trea', lastName: 'Turner' },
      { firstName: 'Ryan', lastName: 'Zimmerman' },
      { firstName: 'Adam', lastName: 'Eaton' },
      { firstName: 'Victor', lastName: 'Robles' },
      { firstName: 'Juan', lastName: 'Soto' },
      { firstName: 'Andrew', lastName: 'Stevenson' },
      { firstName: 'Michael', lastName: 'A.' }
    ]
  } 
];

export const teamUrlCodes = [
  'bal',
  'bos',
  'cws',
  'cle',
  'det',
  'hou',
  'kc',
  'ana',
  'min',
  'nyy',
  'oak',
  'sea',
  'tb',
  'tex',
  'tor',
  'ari',
  'atl',
  'chc',
  'cin',
  'col',
  'la',
  'marlins',
  'mil',
  'nym',
  'phi',
  'pit',
  'sd',
  'sf',
  'stl',
  'was',
]
